# Generated by Django 4.1.7 on 2023-04-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C')], max_length=2, null=True)),
                ('summer', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C')], max_length=2, null=True)),
                ('autumn', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C')], max_length=2, null=True)),
                ('spring', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('other_title', models.CharField(max_length=255)),
                ('connect', models.TextField(blank=True, default='')),
                ('add_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'Модератор взял в работу'), ('accepted', 'Модерация прошла успешно'), ('rejected', 'Модерация прошла, информация не принята')], default='new', max_length=10)),
                ('coord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='pereval_app.coord')),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('img', models.BinaryField()),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
        migrations.CreateModel(
            name='PerevalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
            ],
            options={
                'db_table': 'spr_activities_types',
            },
        ),
        migrations.DeleteModel(
            name='ActivitiesTypes',
        ),
        migrations.RemoveField(
            model_name='images',
            name='pereval',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='coords',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='perevalareas',
            name='id_parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perevalareas',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='perevalareas',
            table='pereval_areas',
        ),
        migrations.DeleteModel(
            name='Coords',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Pereval',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval_app.perevalimages'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='pereval_app.level'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perevals', to='pereval_app.perevaluser'),
        ),
    ]
