# Generated by Django 4.1.7 on 2023-04-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0003_remove_perevalimages_img_alter_perevaladded_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='winter',
            new_name='wiinter',
        ),
    ]
