# Generated by Django 4.1.7 on 2023-04-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0004_rename_winter_level_wiinter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='wiinter',
        ),
        migrations.AddField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C')], max_length=2, null=True),
        ),
    ]
